[versions]
assertj = "3.25.3"
graphql-java = "22.0"
jackson = "2.17.0"
javapoet = "1.13.0"
jetbrains-annotations = "24.1.0"
junit = "5.10.2"
maven-plugin-annotations = "3.11.0"
maven-plugin-api = "3.9.6"
micrometer = "1.12.4"
mockito = "5.11.0"
slf4j = "2.0.12"
spring-boot = "3.2.4"
wiremock = "3.5.4"

[libraries]
assertj-core = { module = "org.assertj:assertj-core", version.ref = "assertj" }
graphql-java = { module = "com.graphql-java:graphql-java", version.ref = "graphql-java" }
jackson-databind = { module = "com.fasterxml.jackson.core:jackson-databind", version.ref = "jackson" }
jackson-datatype-jsr310 = { module = "com.fasterxml.jackson.datatype:jackson-datatype-jsr310", version.ref = "jackson" }
javapoet = { module = "com.squareup:javapoet", version.ref = "javapoet" }
jetbrains-annotations = { module = "org.jetbrains:annotations", version.ref = "jetbrains-annotations" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit" }
junit-jupiter-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit" }
maven-core = { module = "org.apache.maven:maven-core", version.ref = "maven-plugin-api" }
maven-plugin-annotations = { module = "org.apache.maven.plugin-tools:maven-plugin-annotations", version.ref = "maven-plugin-annotations" }
maven-plugin-api = { module = "org.apache.maven:maven-plugin-api", version.ref = "maven-plugin-api" }
micrometer-core = { module = "io.micrometer:micrometer-core", version.ref = "micrometer" }
mockito-core = { module = "org.mockito:mockito-core", version.ref = "mockito" }
slf4j-api = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }
spring-boot-autoconfigure = { module = "org.springframework.boot:spring-boot-autoconfigure", version.ref = "spring-boot" }
wiremock = { module = "org.wiremock:wiremock-standalone", version.ref = "wiremock" }

[bundles]
jackson = ["jackson-databind", "jackson-datatype-jsr310"]
